export const locators = {
    loginTitle: '.login_logo',
    loginForm: '#login_button_container',
    usernameInput: '[data-test="username"]',
    passwordInput: '[data-test="password"]',
    loginButton: '[data-test="login-button"]',
    authError: '[data-test="error"]',
    inventoryItem: '.inventory_item',
    inventoryItemName: '.inventory_item_name',
    inventoryDesc: '.inventory_item_desc',
    inventoryItemPrice: '.inventory_item_price',
    priceButton: '.pricebar button',
    productImg: '.inventory_details_img',
    productName: '.inventory_details_name',
    productDesc: '.inventory_details_desc',
    productPrice: '.inventory_details_price',
    productAddToCart: '.btn_inventory',
    shoppingCartBadge: '.shopping_cart_badge',
    shoppingCartLink: '.shopping_cart_link',
    checkOutBtn: '#checkout',
    cartTitle: '.header_secondary_container .title',
    firstName: '[data-test="firstName"]',
    lastName: '[data-test="lastName"]',
    postalCode: '[data-test="postalCode"]',
    cartContinueBtn: '#continue',
    cartFinishBtn: '#finish',
    cartSummary: '.summary_info',
    footerContainer: '.footer'
  };